USE COMERCIO_OLTP
GO



DECLARE

	@ID_CLIENTE INT, @ID_VENDEDOR INT, @ID_FORMA INT, @DATA DATE

BEGIN

	SET @ID_CLIENTE = 
	(SELECT TOP 1 IDCLIENTE FROM CLIENTE ORDER BY NEWID())

	SET @ID_VENDEDOR =
	(SELECT TOP 1 IDVENDEDOR FROM VENDEDOR ORDER BY NEWID())

	SET @ID_FORMA =
	(SELECT TOP 1 IDFORMA FROM FORMA_PAGAMENTO ORDER BY NEWID())

	SET @DATA = (SELECT
				CONVERT(DATE, CONVERT(VARCHAR(15), '2015-' +
				CONVERT(VARCHAR(5),(CONVERT(INT,RAND()*12)) + 1) +
				'-' +
				CONVERT(VARCHAR(5), (CONVERT(INT,RAND()*27)) + 1))))

	INSERT INTO NOTA_FISCAL(ID_CLIENTE, ID_VENDEDOR, ID_FORMA, DATA) VALUES
	(@ID_CLIENTE, @ID_VENDEDOR, @ID_FORMA, @DATA)



END
GO 8000

select * from nota_fiscal
go

SELECT COUNT(*) FROM NOTA_FISCAL
GO